# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

jobs:
  one: 
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first Hello"
      - run: mkdir -p my_workspace_one
      - run: echo "trying out workspace" > my_workspace_one/echo-output
      - persist_to_workspace:
          root: my_workspace_one
          paths: 
            - echo-output
      
  two: 
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A second Hello"
      - attach_workspace:
        at: my_workspace_one
#       - run: |
#            if [[ $(cat my_workspace_one/echo-output) === "trying out workspace" ]]; then
#             echo "Worked";
#            else
#             echo "Nope"; exit 1
#            fi
           
      
      
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
      
 
